<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<PublishAot>true</PublishAot>
		<InvariantGlobalization>true</InvariantGlobalization>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\QuickFixCli\QuickFixCli.csproj" />
	</ItemGroup>

	<ItemGroup>
		<None Update="dev1.cfg">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="dev2.cfg">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="FIX44.xml">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>
</Project>
